variable "aws_region" {}
variable "s3_bucket_name" {}
variable "project_name" {}
variable "aws_access_key_id" {}
variable "aws_secret_access_key" {}
variable "vpc_cidr" {}
variable "pub_sub_1a_cidr" {}
variable "pub_sub_2b_cidr" {}
variable "pri_sub_3a_cidr" {}
variable "pri_sub_4b_cidr" {}
variable "pri_sub_5a_cidr" {}
variable "pri_sub_6b_cidr" {}
variable "certificate_domain_name" {}
variable "additional_domain_name" {}
#variable "aws_access_key_id" {}
variable "alb_sg" {}
#variable "aws_secret_access_key" {}
variable "alb_dns_name" {}